language: erlang

env:
   - ST=PharoCore-1.1
   - ST=PharoCore-1.2
   - ST=PharoCore-1.3
   - ST=Pharo-1.4
#   - ST=Pharo-3.0 #Pharo-3.0 not ready for testing yet
   - ST=Squeak-4.3
   - ST=Squeak-4.4
   - ST=Squeak-4.5
#  Preview loaded into GemStone (needed for travis support), not testing 1.0-beta.31.1.*

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script: $PROJECT_HOME/tests/testTravisCI.sh -verbose
