language: smalltalk
sudo: false

os:
  - linux

smalltalk_edge:
  source: hpi-swa/smalltalkCI
  branch: dkh-1

smalltalk_config:
  - .smalltalkA.ston
  - .smalltalkB.ston

smalltalk:
  - GemStone-3.3.1
  - Pharo-5.0
  - Squeak-5.0
  - GemStone-2.4.8
  - GemStone-3.1.0.6
  - GemStone-3.2.15
  - Pharo-3.0
  - Pharo-4.0
  - Pharo-6.0
  - Squeak-4.5
  - Squeak-4.6
  - Squeak-trunk

matrix:
  allow_failures:
    - smalltalk: Squeak-4.4
    - smalltalk: Squeak-4.5
    - smalltalk: Squeak-4.6
    - smalltalk: Squeak-5.0
    - smalltalk: Squeak-Trunk
    - smalltalk: Pharo-6.0

cache:
  directories:
    - $SMALLTALK_CI_CACHE
