language: erlang

env:
   - ST=PharoCore-1.3 TRAVIS_SCRIPT=travisCI.st
   - ST=PharoCore-1.3 TRAVIS_SCRIPT=travisPreviewCI.st
   - ST=Pharo-1.4 TRAVIS_SCRIPT=travisCI.st     # until Issue #72 fixed
   - ST=Pharo-1.4 TRAVIS_SCRIPT=travisPreviewCI.st
#   - ST=Pharo-2.0 TRAVIS_SCRIPT=travisCI.st     # until Issue #65 fixed
#   - ST=Pharo-2.0 TRAVIS_SCRIPT=travisPreviewCI.st
   - ST=Squeak4.3 TRAVIS_SCRIPT=travisCI.st
   - ST=Squeak4.3 TRAVIS_SCRIPT=travisPreviewCI.st

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script:

   - echo "running: $PROJECT_HOME/tests/$TRAVIS_SCRIPT"
   - ./build.sh -i $ST -s latAmMirror.st -m -f "$PROJECT_HOME/tests/$TRAVIS_SCRIPT" -o travisCI
   - cd "${BUILD_PATH}/travisCI/"
   - if ( test -e PharoDebug.log ); then cat TravisTranscript.txt; fi
   - if ( test -e PharoDebug.log ); then cat PharoDebug.log; fi
   - if ( test -e PharoDebug.log ); then die; fi
   - if ( test -e SqueakDebug.log ); then cat TravisTranscript.txt; fi
   - if ( test -e SqueakDebug.log ); then cat SqueakDebug.log; fi
   - if ( test -e SqueakDebug.log ); then die; fi
   - if ( test -e TravisCISuccess.txt ); then cat TravisCISuccess.txt; fi
   - if ( test -e TravisCIFailure.txt ); then cat TravisTranscript.txt; fi
   - if ( test -e TravisCIFailure.txt ); then cat TravisCIFailure.txt; fi
   - if ( test -e TravisCIFailure.txt ); then die; fi
